# **NOTES**
# 📊 Python for Data Analytics — Detailed Notes

These notes cover essential Python libraries used in **Data Analytics**.

Libraries included in this notebook series:

• NumPy — numerical computing and arrays  
• Pandas — data manipulation and analysis  
• Matplotlib — data visualization  
• Seaborn — statistical data visualization  

---

## 🎯 Purpose of These Notes

These notes are designed to be:

• beginner friendly  
• concept focused  
• detailed and explanatory  
• useful for revision and teaching  

The goal is to create a **complete learning resource for Python in Data Analytics**.

# 📜 Notebook Structure Rules

Every concept in this notebook follows a **consistent learning structure**.

This helps make the notes easy to read, revise, and teach from.

---

## 📌 Concept Structure

Each topic will follow this order of cells:

1️⃣ Concept / Question (Markdown)  
2️⃣ Code Implementation (Code Cell)  
3️⃣ Output Explanation (Markdown)  
4️⃣ Detailed Explanation (Markdown)  
5️⃣ Notes / Tips / Warnings (Markdown)  
6️⃣ Practice Questions (Optional Markdown)

---

## 📌 Code Cell Rules

Code cells must follow these rules:

• contain only code  
• no explanation text inside code  
• output should appear automatically  

Example:

import numpy as np

arr = np.arange(10)

arr

---

## 📌 Explanation Requirements

Every concept explanation should include:

Definition — what the concept means  
Intuition — simple understanding  
Syntax — function structure  
Example explanation — what the code does  
Use cases — where it is used in real work  

---

## 📌 Goal of These Notes

The final notebook should be detailed enough to:

• revise concepts quickly  
• teach beginners  
• share with others  
• serve as a reference guide

# 🔢 NumPy for Data Analytics

NumPy is one of the most important libraries used in **data analytics and numerical computing**.

It provides powerful tools for working with **arrays, matrices, and numerical data efficiently**.

In data analytics workflows, NumPy is often used for:

• numerical calculations  
• data transformations  
• mathematical operations  
• preparing data for analysis

## ⚙️ Installing NumPy

Before using NumPy, the library must be installed in the Python environment.

NumPy can be installed using **pip**, which is Python's package manager.

---

### 💻 Installation Command

```bash
pip install numpy
```

In [3]:
!pip install numpy

## 📖 Explanation

### pip

`pip` is the **Python package installer** used to install external libraries.

It downloads packages from the **Python Package Index (PyPI)**.

---

### install

The `install` command tells pip to **download and install the specified package**.

---

### numpy

`numpy` is the name of the library being installed.

---

## 🔎 What Happens During Installation

When the command runs:

1. pip searches for NumPy on **PyPI (Python Package Index)**  
2. The package files are downloaded  
3. NumPy is installed into Python's **site-packages directory**

Example location (Windows):

PythonXX/Lib/site-packages

After installation, the library can be used in Python programs by importing it.

## 🔍 Checking the NumPy Version

Before starting serious work with a library, it is often useful to check **which version of the library is installed**.

In Python, many libraries provide a special attribute called `__version__` that stores the version number of the installed package.

NumPy also provides this attribute, which allows us to quickly verify the installed version.

Checking the version is important because:

• different versions may introduce new features  
• some functions behave differently across versions  
• certain tutorials or projects require specific versions  
• debugging problems often requires knowing the library version

In [2]:
import numpy as np 
np.__version__

'2.3.1'

## 📖 Explanation

### 1️⃣ import numpy as np

This line imports the **NumPy library** into the Python program.

• `import` → Python keyword used to load libraries  
• `numpy` → the name of the library  
• `as np` → creates a short alias for easier use

Instead of writing:

numpy.array()

we usually write:

np.array()

Using `np` is the **standard convention used in almost all Python data analysis and scientific computing code**.

---

### 2️⃣ np.__version__

`__version__` is a **special attribute** provided by many Python libraries.

It stores the **version number of the installed library**.

When this line runs, Python retrieves the version information stored inside the NumPy package.

Example output:

2.3.1

---

### 3️⃣ Understanding the Version Number

Library versions usually follow a pattern called **Semantic Versioning**:

Major.Minor.Patch

Example:

2.3.1

Meaning:

• **2** → Major version (big changes or redesigns)  
• **3** → Minor version (new features added)  
• **1** → Patch version (bug fixes or small improvements)

---

### 4️⃣ Why Checking the Version is Important

Checking the library version helps in several situations:

**Compatibility**

Some functions only exist in newer versions.

Example:
A function used in a tutorial might not exist in older versions.

---

**Debugging**

If an error occurs, developers often ask:

"What version of NumPy are you using?"

---

**Reproducibility**

In data analytics and machine learning projects, knowing the exact library version ensures that results can be reproduced.

---

### 5️⃣ Internal Concept

Inside the NumPy package, the version is stored as a variable.

The attribute `__version__` simply returns that stored value.

This allows Python users to quickly inspect the installed library version.

## ❓ Concept

Python lists can store multiple values, but they are not optimized for numerical computation.

NumPy provides a special data structure called a **NumPy array**, which is designed for efficient numerical operations.

### 🎯 Task

Create a NumPy array from the following values:

10, 20, 30, 40, 50

In [2]:
import numpy as np 
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

## 📖 Output & Explanation

🔎 The output displayed is:

[10 20 30 40 50]

📦 This output represents a **NumPy array** containing the values that were originally provided in the Python list.

Although the input was written using a Python list:

[10, 20, 30, 40, 50]

the function `np.array()` converts the list into NumPy’s internal data structure called an **ndarray (N-dimensional array)**.

---

### 🔄 What Changed From the Python List

🐍 **Python list representation**

[10, 20, 30, 40, 50]

🔢 **NumPy array representation**

[10 20 30 40 50]

The commas disappear because NumPy displays array elements using its **own compact numerical format**.

📊 This format is designed to make arrays easier to read when working with **large datasets or multidimensional arrays**.

---

### ⚙ What Happened Internally

When the statement runs:

arr = np.array([10, 20, 30, 40, 50])

NumPy performs several steps:

1️⃣ It receives the Python list as input.  
2️⃣ It determines the **data type** of the elements.  
3️⃣ It allocates **contiguous memory** for storing the elements.  
4️⃣ It stores the values inside a structure called an **ndarray object**.

🧠 The **ndarray** is the **core data structure used by NumPy**.

---

### 🚀 Why NumPy Arrays Are Important

NumPy arrays are designed for **numerical computation and data processing**.

They allow:

⚡ fast mathematical calculations  
💾 efficient memory usage  
📊 vectorized operations on entire datasets  
🧮 support for matrix and statistical operations  

Because of these advantages, NumPy arrays are widely used in:

📈 data analytics  
🤖 machine learning  
🔬 scientific computing

## ❓ Concept

After creating a NumPy array, we often need to understand its **structure and properties**.

NumPy arrays provide several built-in attributes that describe the array, such as:

• number of dimensions  
• shape of the array  
• total number of elements  
• data type of elements

These attributes help us analyze and manipulate arrays more effectively.

In [ ]:
import numpy as np 

# recreate the example array
arr = np.array([10,20,30,40,50])
arr.ndim , arr.shape , arr.size , arr.dtype

(1, (5,), 5, dtype('int64'))

## 📖 Output & Explanation

The output produced may look similar to this:

(1, (5,), 5, dtype('int32'))  
or  
(1, (5,), 5, dtype('int64'))

This output contains **four values**, each describing a different **property of the NumPy array**.

---

### 📏 `arr.ndim` — Number of Dimensions

`ndim` returns the **number of dimensions of the array**.

Output:

1

This means the array is **one-dimensional (1D)**.

A 1D array behaves like a simple list of values arranged in a single row.

---

### 📐 `arr.shape` — Shape of the Array

`shape` describes the **structure of the array**.

Output:

(5,)

This means the array contains **5 elements in a single dimension**.

For multi-dimensional arrays, shape would show **rows and columns**.

Example concept:

(3,4) → 3 rows and 4 columns.

---

### 🔢 `arr.size` — Total Number of Elements

`size` returns the **total number of elements stored in the array**.

Output:

5

This confirms that the array contains **five numerical values**.

---

### 🧬 `arr.dtype` — Data Type of Elements

`dtype` shows the **data type of the elements stored in the NumPy array**.

Example outputs:

dtype('int32')  
or  
dtype('int64')

The exact integer type depends on the **system architecture and Python installation**.

Both represent **integer data types used to store numbers efficiently in memory**.

---

### 🚀 Why These Attributes Are Important

Array attributes help us understand the **structure and characteristics of data** stored in NumPy arrays.

They are useful for:

📊 analyzing datasets  
🧠 debugging array operations  
⚙ preparing data for machine learning models  
📈 performing numerical computations

## ❓ Concept

So far we created a **1D NumPy array**.

However, NumPy is designed to work with **multi-dimensional data**.

A very common structure is a **2D array**, which represents data in **rows and columns**, similar to a table or spreadsheet.

2D arrays are widely used in:

📊 data analytics  
📈 datasets  
🤖 machine learning

In [ ]:
import numpy as np 
matrix = np.array([
    [10,20,30],
    [40,50,60]
])
matrix

array([[10, 20, 30],
       [40, 50, 60]])

## 📖 Output & Explanation

The output represents a **2D NumPy array**:

[[10 20 30],

 [40 50 60]]

This array contains:

• **2 rows**  
• **3 columns**

In NumPy, this structure is often called a **matrix-like array**.

---

### 🧠 How It Was Created

The array was created using a **nested list**.

Outer list → represents rows  
Inner lists → represent columns

Example structure:

[
    
 [10, 20, 30],

 [40, 50, 60]
]

NumPy converts this nested list into a **2-dimensional ndarray**.

---

### 🚀 Why 2D Arrays Are Important

Most real-world datasets are **tabular**, meaning they have:

rows → records  
columns → features

NumPy uses 2D arrays to represent this kind of structured data efficiently.

## ❓ Concept

NumPy arrays are not limited to one or two dimensions.  
They can also represent **three-dimensional structures**, often called **3D arrays**.

A 3D array can be thought of as a **collection of multiple 2D arrays stacked together**.

These structures are useful for representing data such as:

📊 time-series datasets  
🖼 image data (height × width × channels)  
🔬 scientific simulations

In [ ]:
import numpy as np
arr3D = np.array([
    [[1,2,3],[4,5,6]],
     [[7,8,9],[10,11,12]]])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## 📖 Output & Explanation

🔎 The output displayed is a **3-dimensional NumPy array**.

Example output:

[[[ 1  2  3]

  [ 4  5  6]]

 [[ 7  8  9]

  [10 11 12]]]

At first glance this may look complicated, but it simply represents **multiple 2D arrays stacked together**.

---

### 🧠 Understanding the Structure

A **3D array** can be visualized as **layers of matrices**.

Each layer contains a **2D array**, and multiple layers together form a **3D structure**.

In this example the structure is:

📦 **2 blocks (or layers)**  
📏 **2 rows in each block**  
🔢 **3 columns in each row**

So the array is organized like this:

📄 **Layer 1**

[1 2 3]  
[4 5 6]

📄 **Layer 2**

[7 8 9]  
[10 11 12]

---

### 📐 Shape Representation

NumPy describes array dimensions using the **shape attribute**.

For this array the shape is:

(2, 2, 3)

This means:

📦 **2 blocks (depth dimension)**  
📏 **2 rows in each block**  
🔢 **3 columns in each row**

So the shape follows the pattern:

(depth, rows, columns)

---

### 🔍 Why 3D Arrays Exist

3D arrays are useful when data has **multiple levels of structure**.

For example:

📊 **Time-series datasets**  
Different time periods stored as layers.

🖼 **Images in computer vision**  
Height × Width × Color channels (RGB).

🔬 **Scientific simulations**  
Measurements across space and time.

---

### ⚙ Internal Representation in NumPy

Even though the array looks like nested lists, NumPy stores it internally as a single **ndarray object**.

💾 All values are stored efficiently in **contiguous memory**, which allows NumPy to perform **fast numerical operations** across large datasets.

This is one reason NumPy is widely used in:

📈 data analytics  
🤖 machine learning  
🔬 scientific computing

## ❓ Concept

Sometimes we need to create arrays containing a **sequence of numbers**.

Typing many numbers manually is inefficient and error-prone.

NumPy provides the function **np.arange()**, which automatically generates numbers within a specified range.

This function is commonly used when creating **index values, datasets, or numerical sequences**.

In [17]:
import numpy as np
arrAranged = np.arange(10)
arrAranged

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 📖 Output & Explanation

The output produced is:

[0 1 2 3 4 5 6 7 8 9]

This array was automatically generated using the **NumPy function `np.arange()`**.

Instead of manually typing each number, NumPy created the sequence **automatically**.

---

### 🔢 What `np.arange(10)` Means

The function call:

np.arange(10)

tells NumPy to:

• start generating numbers from **0**  
• continue increasing by **1**  
• stop **before reaching 10**

Because the stop value is **exclusive**, the number **10 is not included** in the result.

So the generated sequence becomes:

0 → 1 → 2 → 3 → 4 → 5 → 6 → 7 → 8 → 9

---

### 📊 What the Variable Stores

The variable:

arrAranged

now stores a **NumPy array containing the generated sequence**.

This array can now be used for:

📈 numerical calculations  
📊 data analysis operations  
🔢 indexing and slicing  
⚙ mathematical transformations

---

### 🚀 Why `np.arange()` Is Useful

`np.arange()` is commonly used when we need to:

• generate **index values**  
• create **number sequences**  
• build **datasets for experiments or simulations**  
• prepare values for **plotting graphs**

## ❓ Concept

So far we used `np.arange(10)` to generate numbers from **0 to 9** automatically.

However, NumPy also allows us to control:

• where the sequence **starts**  
• where the sequence **stops**  
• the **step size** between numbers

This is done using the extended form of the function:

np.arange(start, stop, step)

This allows us to generate more flexible numerical sequences.

In [19]:
import numpy as np 
ArrRange = np.arange(1,10,2)
ArrRange

array([1, 3, 5, 7, 9])

## 📖 Output & Explanation

The output produced is:

[1 3 5 7 9]

This sequence was generated using:

np.arange(1, 10, 2)

---

### 🔢 Understanding the Parameters

The function uses three parameters:

• **start → 1**  
The sequence begins at 1.

• **stop → 10**  
The sequence stops before reaching 10.

• **step → 2**  
Each number increases by 2.

---

### 📊 How the Sequence Was Generated

NumPy starts at **1** and keeps adding **2** until it reaches the stopping limit.

1 → 3 → 5 → 7 → 9

Since the stop value **10 is exclusive**, it is **not included** in the result.

---

### 🚀 Why This Is Useful

Using `np.arange(start, stop, step)` allows us to easily create:

📈 custom numeric ranges  
📊 evenly spaced sequences  
⚙ datasets for simulations or calculations

## ❓ Concept

NumPy also allows us to generate a sequence of numbers by specifying only the **start and stop values**.

In this case, the step size is **automatically taken as 1**.

The function format becomes:

np.arange(start, stop)

This is useful when we want a simple sequence with default spacing.

In [1]:
import numpy as np
ArrArange = np.arange(2,10)
ArrArange

array([2, 3, 4, 5, 6, 7, 8, 9])

## 📖 Output & Explanation

The output produced is:

[2 3 4 5 6 7 8 9]

This sequence was generated using:

np.arange(2, 10)

---

### 🔢 How It Works

• **start → 2**  
The sequence begins from 2.

• **stop → 10**  
The sequence stops before reaching 10.

• **step → 1 (default)**  
Since no step is given, NumPy automatically uses a step of 1.

---

### 📊 Sequence Generation

NumPy starts at 2 and keeps adding 1:

2 → 3 → 4 → 5 → 6 → 7 → 8 → 9

The value 10 is **not included** because the stop value is **exclusive**.

---

### 🚀 Why This Version Is Useful

This form is commonly used when:

📊 generating simple ranges  
📈 creating index sequences  
🔢 preparing data for iteration or calculations

## ❓ Concept

So far we used `np.arange()` to generate numbers based on a **step size**.

However, sometimes we need to generate a **fixed number of values between two numbers**, instead of controlling the step.

NumPy provides the function **np.linspace()**, which generates **evenly spaced numbers** between a start and stop value.

This function is commonly used in:

📈 plotting graphs  
📊 data analysis  
🔬 scientific computations

In [2]:
import numpy as np
arrLineSpace = np.linspace(0, 10, 5)
arrLineSpace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## 📖 Output & Explanation

The output produced is:

[ 0.   2.5  5.   7.5 10. ]

This sequence was generated using:

np.linspace(0, 10, 5)

---

### 🔢 Understanding the Parameters

• **start → 0**  
The sequence begins at 0.

• **stop → 10**  
The sequence ends at 10.

• **5 → number of values**  
NumPy generates exactly 5 evenly spaced values.

---

### 📊 How the Values Are Generated

NumPy divides the interval from **0 to 10** into equal parts.

So the spacing becomes:

0 → 2.5 → 5 → 7.5 → 10

Unlike `np.arange()`, the **stop value IS included** here.

---

### 🔥 Key Difference from `arange()`

📌 `np.arange()` → uses **step size**  
📌 `np.linspace()` → uses **number of values**

---

### 🚀 Why `np.linspace()` Is Useful

This function is widely used when:

📈 generating smooth values for graphs  
📊 creating evenly spaced datasets  
🔬 simulations requiring precise intervals

## ❓ Concept

By default, `np.linspace()` **includes the stop value** in the generated sequence.

However, in some cases we may want to **exclude the stop value**, similar to how `np.arange()` works.

NumPy provides an optional parameter:

endpoint=False

This allows us to generate evenly spaced values **without including the final value**.

In [3]:
import numpy as np 
arrLineSpace = np.linspace(0, 10, 5, endpoint=False)
arrLineSpace

array([0., 2., 4., 6., 8.])

## 📖 Output & Explanation

The output produced is:

[0. 2. 4. 6. 8.]

This sequence was generated using:

np.linspace(0, 10, 5, endpoint=False)

---

### 🔢 What Changed?

Normally:

np.linspace(0,10,5)

gives:

[0.  2.5  5.  7.5 10.]

But with:

endpoint=False

the value **10 is excluded**.

---

### 📊 How Values Are Generated

NumPy divides the range into equal parts but **does not include the stop value**.

So spacing becomes:

0 → 2 → 4 → 6 → 8

---

### 🔥 Important Difference

📌 Default → stop value **included**  
📌 endpoint=False → stop value **excluded**

---

### 🚀 Why This Is Useful

This is useful when:

📈 matching behavior similar to `arange()`  
📊 creating intervals without overlap  
🔬 simulations requiring strict boundaries

## ❓ Concept

Sometimes we need to create arrays that are filled entirely with **zeros or ones**.

Instead of manually writing values, NumPy provides built-in functions:

• `np.zeros()` → creates an array filled with zeros  
• `np.ones()` → creates an array filled with ones  

These functions are commonly used when we need to **initialize arrays before performing calculations or data processing**.

In [4]:
import numpy as np 
zeros_arr = np.zeros(5)
ones_arr = np.ones(5)

zeros_arr, ones_arr

(array([0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))

## 📖 Output & Explanation

The output produced is:

(array([0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))

---

### 🔢 Understanding the Functions

• `np.zeros(5)`  
Creates an array with **5 elements**, all initialized to **0**.

• `np.ones(5)`  
Creates an array with **5 elements**, all initialized to **1**.

---

### 📊 Why Values Have Decimal Points

The values appear as:

0.  and  1.

This indicates that NumPy created the arrays with a **floating-point data type (float64)** by default.

---

### 📐 Array Size

The number inside the function:

5

represents the **number of elements in the array**.

So both arrays contain **5 elements**.

---

### 🚀 Why These Functions Are Important

These functions are widely used for:

📊 initializing datasets  
🤖 preparing inputs for machine learning models  
🔬 creating base arrays for numerical operations  
⚙ setting default values before modifying data

## ❓ Concept

So far we created **1D arrays** using `np.zeros()` and `np.ones()`.

However, NumPy also allows us to create **multi-dimensional arrays** filled with zeros or ones.

To create a 2D array, we pass a **tuple representing (rows, columns)**.

This allows us to create matrix-like structures filled with default values.

In [3]:
import numpy as np 
ZerosArr2D = np.zeros((2,3))
OnesArr2D = np.ones((2,3))
ZerosArr2D , OnesArr2D

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

## 📖 Output & Explanation

The output produced is:

(array([[0., 0., 0.],

        [0., 0., 0.]]),


 array([[1., 1., 1.],

        [1., 1., 1.]]))

---

### 📐 Understanding the Shape

The input:

(2, 3)

means:

📏 2 rows  
🔢 3 columns  

So NumPy creates a **2D array (matrix)** with this structure.

---

### 🔢 What Each Function Does

• `np.zeros((2,3))`  
Creates a 2×3 matrix filled with **0**

• `np.ones((2,3))`  
Creates a 2×3 matrix filled with **1**

---

### 📊 Why This Is Useful

These are commonly used for:

📊 initializing tables or datasets  
🤖 preparing matrices for machine learning  
🔬 simulations and numerical computations  

---

### ⚠ Important Note

The shape must be passed as a **tuple**:

(2,3)

If you write:

np.zeros(2,3) ❌

it will give an error.

## ❓ Concept

By default, `np.zeros()` and `np.ones()` create arrays with a **floating-point data type (float64)**.

However, NumPy allows us to control the **data type of the array elements** using the `dtype` parameter.

This is useful when we want arrays of:

• integers  
• floats  
• other numeric types  

instead of the default float values.

In [5]:
import numpy as np
ZerosArrAsInt = np.zeros(5,dtype=int)
OnesArrAsInt = np.ones(5, dtype=int)
ZerosArrAsInt , OnesArrAsInt

(array([0, 0, 0, 0, 0]), array([1, 1, 1, 1, 1]))

## 📖 Output & Explanation

The output produced is:

(array([0, 0, 0, 0, 0]), array([1, 1, 1, 1, 1]))

---

### 🔢 What Changed?

Earlier, we saw outputs like:

0.  and  1.

These were **floating-point numbers**.

Now, using:

dtype=int

the values are stored as **integers**:

0 and 1 (without decimal points)

---

### ⚙ Understanding `dtype`

`dtype` stands for **data type**.

It tells NumPy what type of values to store in the array.

Examples:

• `dtype=int` → integers  
• `dtype=float` → floating-point numbers  

---

### 🚀 Why This Is Important

Controlling data type helps in:

💾 memory optimization  
⚡ faster computations  
📊 ensuring correct data representation  

For example, integers use less memory than floating-point numbers in many cases.

## ❓ Concept

In addition to specifying the shape and data type, NumPy allows us to create **multi-dimensional arrays of any size** using `np.zeros()` and `np.ones()`.

These functions can be used to create:

• 1D arrays  
• 2D arrays  
• 3D arrays and higher  

by passing a tuple that represents the dimensions of the array.

In [8]:
import numpy as np 
ZerosArr3D = np.zeros((2,2,3))
OnesArr3D = np.ones((2,2,3))
ZerosArr3D, OnesArr3D

(array([[[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]]]))

## 📖 Output & Explanation

🔎 The output represents a **3-dimensional NumPy array** where all elements are either **0** or **1**, depending on the function used.

Example structure (zeros):

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

---

### 🧠 Understanding the 3D Structure

A 3D array can be visualized as a **stack of 2D arrays (matrices)**.

Think of it like:

📦 multiple layers  
📄 each layer is a table (2D array)  
🔢 each table contains rows and columns  

---

### 📐 Breaking Down the Shape

The shape given is:

(2, 2, 3)

This follows the pattern:

(depth, rows, columns)

Meaning:

📦 2 layers (or blocks)  
📏 each layer has 2 rows  
🔢 each row has 3 elements  

---

### 🧾 Visual Representation

Layer 1:

[0 0 0]  
[0 0 0]  

Layer 2:

[0 0 0]  
[0 0 0]  

So overall, we have **2 separate 2D arrays stacked together**.

---

### ⚙ What NumPy Does Internally

Even though the array looks like nested lists, NumPy does NOT store it like Python lists.

Instead, NumPy:

1️⃣ Allocates a single block of **contiguous memory**  
2️⃣ Stores all values in a structured format  
3️⃣ Uses indexing rules to access elements across dimensions  

This is why NumPy arrays are:

⚡ faster  
💾 memory-efficient  
📊 optimized for numerical operations  

---

### 🔢 Role of `np.zeros()` and `np.ones()`

• `np.zeros((2,2,3))`  
Creates a structured array filled entirely with **0**

• `np.ones((2,2,3))`  
Creates the same structure but filled with **1**

These are often used as **initial base arrays** before applying operations.

---

### 🧬 Data Type Insight

Even though we wrote `0` and `1`, NumPy stores them as:

0.  and  1.

This indicates the default type is:

float64

This allows NumPy to handle **decimal and scientific calculations** efficiently.

---

### 🚀 Real-World Importance

3D arrays are used in many real-world scenarios:

🖼 Image processing → (height × width × color channels)  
📊 Time-series data → (time × features × samples)  
🤖 Machine learning → multi-dimensional datasets  
🔬 scientific simulations → spatial + temporal data  

---

### 💡 Key Takeaway

A 3D NumPy array is simply a **collection of 2D arrays organized in layers**, stored efficiently in memory and designed for high-performance numerical computation.

## ❓ Concept

In many mathematical and data science applications, we need a special type of matrix called an **Identity Matrix**.

An identity matrix is a square matrix where:

• all diagonal elements are **1**  
• all other elements are **0**

NumPy provides the function **np.eye()** to create identity matrices easily.

This is commonly used in:

📊 linear algebra  
🤖 machine learning  
🔬 scientific computations

In [9]:
import numpy as np 
IdetityMatrix = np.eye(3)
IdetityMatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 📖 Output & Explanation

🔎 The output produced is:

[[1. 0. 0.]

 [0. 1. 0.]
 
 [0. 0. 1.]]

This is a **3 × 3 identity matrix**, a special type of square matrix used in mathematics and data science.

---

### 🧠 Understanding the Identity Matrix

An identity matrix is defined as a matrix where:

• all elements on the **main diagonal** are **1**  
• all other elements are **0**

It acts as the **multiplicative identity in matrix algebra**.

---

### 📐 Visualizing the Matrix

Matrix:

[1 0 0]  
[0 1 0]  
[0 0 1]  

📍 Diagonal positions:

(0,0), (1,1), (2,2)

These positions contain **1**, while all other positions contain **0**.

---

### 🔢 Why the Diagonal Matters

The diagonal represents positions where:

row index = column index

Example:

matrix[i, j]

If:

i == j → value = 1  
i ≠ j → value = 0  

This rule defines an identity matrix.

---

### ⚙ How `np.eye()` Works Internally

The function:

np.eye(3)

performs the following steps:

1️⃣ Creates an empty 3×3 array  
2️⃣ Iterates over diagonal positions  
3️⃣ Assigns value **1** where row = column  
4️⃣ Fills all other positions with **0**

Result → structured identity matrix

---

### 🧬 Data Type Insight

The output shows:

1. and 0.

This indicates NumPy uses:

float64 (default)

Even though values look like integers, they are stored as **floating-point numbers** for numerical consistency.

---

### 🔁 Mathematical Importance

Identity matrices behave like the number **1** in multiplication.

Example:

A × I = A  
I × A = A  

This means multiplying any matrix by an identity matrix **does not change the matrix**.

---

### 📊 Practical Applications

Identity matrices are used in:

📊 linear algebra computations  
🤖 machine learning algorithms  
🔬 solving systems of equations  
📈 matrix transformations  

---

### 🚀 Advanced Insight

Identity matrices are also used to:

• create inverse matrices  
• perform transformations  
• stabilize numerical computations  

They are a **foundation concept in matrix-based calculations**.

---

### 💡 Key Takeaway

An identity matrix is a **structured matrix with 1s on the diagonal and 0s elsewhere**, acting as the **neutral element in matrix multiplication** and forming a core building block in numerical computing.

## ❓ Concept

The function `np.eye()` can also create **non-square (rectangular) matrices**.

By providing two values, we can control:

• number of rows  
• number of columns  

This allows us to create identity-like matrices that are not necessarily square.

In [12]:
import numpy as np
RectangleMatrix = np.eye(3,4)
RectangleMatrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## 📖 Output & Explanation

🔎 The output produced is:

[[1. 0. 0. 0.]

 [0. 1. 0. 0.]
 
 [0. 0. 1. 0.]]

This represents a **rectangular identity-like matrix** created using:

np.eye(3, 4)

---

### 📐 Understanding the Shape

The function:

np.eye(3, 4)

creates a matrix with:

📏 3 rows  
🔢 4 columns  

So the structure is:

3 × 4 matrix

This means:

• total rows = 3  
• total columns = 4  

---

### 🧠 How NumPy Decides Where to Place 1s

NumPy follows a rule based on **index positions**:

For each element:

matrix[i, j]

If:

i == j → value = 1  
i ≠ j → value = 0  

---

### 🔢 Applying This Rule to a Rectangular Matrix

Let’s check positions:

Row 0 → (0,0) → 1  
Row 1 → (1,1) → 1  
Row 2 → (2,2) → 1  

But notice:

There is **no (3,3)** because we only have **3 rows**.

So the diagonal stops early.

---

### 📊 Why the Diagonal Stops

The diagonal length is determined by:

min(rows, columns)

Here:

min(3,4) = 3

So only **3 diagonal elements** can exist.

That’s why:

✔ 3 ones  
✔ remaining positions are zero  

---

### 🧾 Visual Breakdown

Matrix:

[1 0 0 0]  
[0 1 0 0]  
[0 0 1 0]  

👉 Notice:

The **last column has no diagonal element**, so it remains all zeros.

---

### ⚙ Internal Logic (Important Insight)

Internally, NumPy:

1️⃣ Creates a full 3×4 matrix of zeros  
2️⃣ Iterates along diagonal positions  
3️⃣ Assigns 1 only where **row index = column index**  

Everything else remains zero.

---

### 🔬 Mathematical Interpretation

This is not a “true identity matrix” because:

✔ identity matrix must be **square (n × n)**  
❌ this is **rectangular (3 × 4)**  

So this is called:

👉 **identity-like matrix**

---

### 🚀 Why This Matters

Rectangular identity matrices are useful in:

📊 matrix transformations  
🔬 numerical computations  
🤖 machine learning preprocessing  
📈 linear algebra operations involving non-square matrices  

---

### 💡 Key Takeaway

`np.eye(rows, cols)` creates a matrix where:

✔ diagonal follows index rule (i == j)  
✔ diagonal length = min(rows, cols)  
✔ matrix may be rectangular, not strictly identity  

This gives flexibility in constructing structured matrices for advanced computations.

## ❓ Concept

NumPy allows us to shift the diagonal using the parameter:

k

This controls which diagonal is filled with **1s**.

• k = 0 → main diagonal (default)  
• k > 0 → above main diagonal  
• k < 0 → below main diagonal  

This provides flexibility in creating shifted identity matrices.

In [14]:
import numpy as np 
UpperDiag = np.eye(3, k=1)
Lower_Diag = np.eye(3, k=-1)
UpperDiag , Lower_Diag

(array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]]),
 array([[0., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.]]))

## 📖 Output & Explanation

🔎 The output shows two matrices where the **diagonal of 1s has been shifted** from its original position.

---

### 🔼 Upper Diagonal (k = 1)

[[0. 1. 0.]

 [0. 0. 1.]

 [0. 0. 0.]]

Here, the diagonal is shifted **one position above the main diagonal**.

---

### 🔽 Lower Diagonal (k = -1)

[[0. 0. 0.]

 [1. 0. 0.]
 
 [0. 1. 0.]]

Here, the diagonal is shifted **one position below the main diagonal**.

---

### 🧠 Understanding the Diagonal Shift (Core Logic)

In a normal identity matrix:

matrix[i, j]

we place **1** when:

i == j

---

### ⚙ What Happens When We Use `k`

NumPy modifies the condition to:

i == j - k

This means:

• when **k = 0** → i == j (main diagonal)  
• when **k = 1** → diagonal shifts **up**  
• when **k = -1** → diagonal shifts **down**

---

### 📐 Index-Based Explanation

Let’s analyze positions for k = 1:

We place 1 where:

i == j - 1

Example:

(0,1) → 1  
(1,2) → 1  

So the diagonal moves **one column to the right**, which visually appears **above**.

---

For k = -1:

Condition:

i == j + 1

Example:

(1,0) → 1  
(2,1) → 1  

So the diagonal moves **one column to the left**, appearing **below**.

---

### 📊 Visual Understanding

Main diagonal (k=0):

[1 0 0]  
[0 1 0]  
[0 0 1]  

Shift up (k=1):

[0 1 0]  
[0 0 1]  
[0 0 0]  

Shift down (k=-1):

[0 0 0]  
[1 0 0]  
[0 1 0]  

---

### ⚙ Internal Behavior of NumPy

Internally, NumPy:

1️⃣ Creates a zero matrix  
2️⃣ Calculates shifted diagonal positions using `k`  
3️⃣ Assigns 1 to those positions  
4️⃣ Leaves all other values as 0  

---

### 🔬 Mathematical Insight

The `k` parameter allows selection of **different diagonals** in a matrix.

These are called:

• main diagonal → k = 0  
• superdiagonal → k > 0  
• subdiagonal → k < 0  

---

### 🚀 Why This Is Important

Shifted diagonals are used in:

📊 matrix transformations  
🔬 numerical methods (finite differences)  
🤖 machine learning (structured matrices)  
📈 linear algebra operations  

---

### 💡 Key Takeaway

The `k` parameter shifts the diagonal by modifying the index rule:

✔ k = 0 → main diagonal  
✔ k > 0 → shift upward  
✔ k < 0 → shift downward  

This provides **precise control over matrix structure**.

## ❓ Concept

In NumPy, not all arrays are 2D.

Sometimes we work with **1D arrays**, which are like simple lists 📏

In this case, indexing becomes easier because we only need **one position value**.

Each element is accessed using a **single index**.

In [2]:
import numpy as np 
Arr1D = np.array([100,20,30,40])
Arr1D[2]

np.int64(30)

## 📖 Output & Explanation

The output produced is:

np.int64(30) 🎯

---

### 🔢 Understanding the Array

The array is:

[10 20 30 40]

Let’s assign index positions:

Index →   0   1   2   3  
Value →  10  20  30  40  

---

### ⚙️ What the Code Did

Arr1D[2]

This means:

👉 Start from the beginning  
👉 Move to position **2**  
👉 Retrieve that value  

So we get:

30 ✅

---

### 🧠 HOW NumPy Thinks

NumPy doesn’t see a list like we do ❌

It sees:

👉 A sequence of memory positions 💾

So:

Arr11D[2] → go to position 2 → fetch value

---

### 🤯 WHY Index Starts From 0

Because in memory:

👉 First element = position 0  
👉 Not 1

This makes calculations faster ⚡

---

### ⚠️ Important Error Case

If you try:

Arr1D[10]

❌ It will give:

IndexError 🚫

Because that position does not exist.

---

### 🚀 WHY This is Important

1D indexing is used in:

• data selection 📊  
• filtering values 🔍  
• slicing arrays ✂️  
• machine learning pipelines 🤖  

---

### 💡 FINAL IDEA

1D Indexing = **accessing elements using one position**

Simple, fast, and fundamental 🔥

## ❓ Concept

In NumPy, we can also access elements **from the end of the array** 🔁

This is done using **negative indexing**.

Instead of starting from the beginning, indexing starts from the **last element**.

In [1]:
import numpy as np 
NegativeArray = np.array([10,20,30,40])
NegativeArray[-1]

np.int64(40)

## 📖 Output & Explanation

The output produced is:

np.int64(40) 🎯

---

### 🔢 Understanding the Array

The array is:

[10 20 30 40]

Let’s map positions:

Positive indexing:

0 → 10  
1 → 20  
2 → 30  
3 → 40  

Negative indexing:

-1 → 40  
-2 → 30  
-3 → 20  
-4 → 10  

---

### ⚙️ What the Code Did

arr[-1]

This means:

👉 Start from the **end of the array**  
👉 Move 1 step backward  
👉 Retrieve that value  

So we get:

40 ✅

---

### 🧠 IMPORTANT — Actual Output Type

The result is NOT just `40`

It is:

np.int64(40)

👉 This means:

• `40` = value  
• `np.int64` = **data type (NumPy integer)**  

---

### 🤯 WHY NumPy Returns np.int64

NumPy does NOT use normal Python integers ❌

It uses its own optimized types:

• np.int32  
• np.int64  
• np.float64  

👉 Why?

Because:

• better performance ⚡  
• fixed memory usage 💾  
• faster mathematical operations 🧮  

---

### 🧠 HOW NumPy Thinks

Negative indexing means:

👉 Count positions from the end 🔁

So internally:

arr[-1] → last memory position  
arr[-2] → second last  

---

### 📦 Memory-Level Insight (ADVANCED 🔥)

Array in memory:

[10, 20, 30, 40]

Stored as continuous block:

Index:   0   1   2   3  
Value:  10  20  30  40  

Negative indexing converts:

-1 → 3  
-2 → 2  

👉 So:

arr[-1] → arr[3]

---

### 🤯 WHY This is USEFUL

Because sometimes:

• array size is unknown 📏  
• data keeps changing 🔄  
• we only need recent values ⏱️  

Negative indexing avoids:

❌ calculating length  
❌ writing extra code  

---

### 🚀 REAL USE CASES

• last row of dataset 📊  
• latest stock price 📈  
• recent log entry 🧾  
• last prediction result 🤖  

---

### ⚠️ Edge Case

If you go beyond limit:

arr[-10]

❌ IndexError (out of bounds)

---

### 💡 FINAL IDEA

Negative Indexing = **reverse position access**

👉 Smart  
👉 Fast  
👉 Memory-efficient  

And always remember:

👉 Output is NOT just value  
👉 It is **NumPy typed value (np.int64)** 🔥

## ❓ Concept

Sometimes we don’t need just one element.

We may need **multiple elements from an array** 📦

NumPy provides **slicing** ✂️

Slicing allows us to extract a **range of values** using index positions.

In [3]:
import numpy as np 
Arr = np.array([10,20,30,40,50])
Arr[1:4]

array([20, 30, 40])

## 📖 Output & Explanation

The output produced is:

[20 30 40] 🎯

---

### 🧠 Important Note on Output Format

This is a **NumPy array**, not a Python list.

👉 It looks like:

[20 30 40]

But internally it is:

array([20, 30, 40])

👉 Data type:

<class 'numpy.ndarray'>

---

### 🔢 Understanding the Array

[10 20 30 40 50]

Index →   0   1   2   3   4  
Value →  10  20  30  40  50  

---

### ⚙️ What the Code Did

Arr[1:4]

This means:

👉 Start from index **1**  
👉 Go up to index **4** (but NOT include 4 ❗)

So we get:

20, 30, 40 ✅

---

### 🧠 Important Rule

Slicing follows:

[start : stop]

👉 Start = included ✅  
👉 Stop = excluded ❌  

---

### 🤯 WHY Stop is Excluded

Because NumPy follows Python’s range logic.

This makes slicing consistent and predictable ⚡

---

### 🧠 HOW NumPy Thinks

arr[1:4]

Internally:

→ selects elements at positions 1, 2, 3  

---

### 📦 Output Type

Result is:

👉 NumPy array → ndarray  

---

### 🚀 WHY SLICING IS IMPORTANT

• extract subsets of data 📊  
• preprocessing datasets 🤖  
• selecting features 🔍  
• efficient data handling ⚡  

---

### ⚠️ Edge Case

Arr[1:10] → no error ❗  
👉 automatically stops at last index  

---

### 💡 FINAL IDEA

Slicing = extracting a range using index positions ✂️

Efficient ⚡ Flexible 🔥 Powerful 🚀

## ❓ Concept

Slicing can also control **how many steps to skip** between elements.

This is done using a third value called **step**.

Syntax:

[start : stop : step]

In [7]:
import numpy as np 
Arr = np.array([10,20,30,40,50,60])
Arr[0:6:2]

array([10, 30, 50])

## 📖 Output & Explanation

The output produced is:

[10 30 50] 🎯

---

### 🧠 Important Note on Output

This is a NumPy array:

array([10, 30, 50])

👉 Data type:

<class 'numpy.ndarray'>

Each element inside is:

np.int64

---

### 🔢 Understanding the Array

Original array:

[10 20 30 40 50 60]

Index →   0   1   2   3   4   5  
Value →  10  20  30  40  50  60  

---

### ⚙️ What the Code Did

Arr[0:6:2]

This follows slicing format:

[start : stop : step]

So:

👉 Start = 0  
👉 Stop = 6 (excluded ❗)  
👉 Step = 2  

---

### 🧠 Step-by-Step Execution

NumPy internally does:

1️⃣ Start at index 0 → value = 10  
2️⃣ Add step (2) → move to index 2 → value = 30  
3️⃣ Add step (2) → move to index 4 → value = 50  
4️⃣ Next would be index 6 → ❌ stop (excluded)

---

### 🔁 How Step Works (CORE LOGIC)

Step means:

👉 “Jump this many positions each time”

So:

step = 2 → skip 1 element every time

---

### 📦 Internal Thinking (VERY IMPORTANT 🔥)

NumPy treats array as:

continuous memory block 💾

[10, 20, 30, 40, 50, 60]

Then applies:

→ start at memory position 0  
→ jump by 2 positions repeatedly  

So internally:

0 → 2 → 4  

---

### 🤯 WHY STEP SLICING EXISTS

Because in real problems:

• we don’t always need all data ❌  
• we need patterns or samples 📊  

Example:

👉 Take every 2nd value  
👉 Downsample dataset  
👉 Reduce computation  

---

### 🚀 REAL USE CASES

• sampling large datasets 📊  
• image processing (pixel skipping) 🖼️  
• time-series analysis ⏱️  
• performance optimization ⚡  

---

### ⚠️ Important Edge Cases

1️⃣ If step > range:

Arr[0:6:10] → [10]

2️⃣ If step = 1:

Normal slicing (no skipping)

3️⃣ If step is negative:

Reverse slicing 🔁 (we’ll see next)

---

### 💡 FINAL IDEA

Step slicing = **controlled movement through array**

👉 Not just selecting data  
👉 But controlling HOW we traverse data 🔥

## ❓ Concept

NumPy slicing can also work in reverse 🔁

By using a **negative step value**, we can traverse the array **from end to start**.

This is called **reverse slicing**.

In [ ]:
import numpy as np 
ReversedArr = np.array(
    [10,20,30,40,50]
    )
ReversedArr[::-1]

array([50, 40, 30, 20, 10])

## 📖 Output & Explanation

The output produced is:

[50 40 30 20 10] 🎯

---

### 🧠 Output Type

array([50, 40, 30, 20, 10])  
<class 'numpy.ndarray'>

Each element → np.int64

---

### 🔢 Understanding the Array

Original array:

[10 20 30 40 50]

Index →   0   1   2   3   4  

---

### ⚙️ What the Code Did

ReversedArr[::-1]

This means:

👉 Start = default (end of array)  
👉 Stop = default (before start)  
👉 Step = -1  

---

### 🧠 Step-by-Step Execution

NumPy internally does:

1️⃣ Start at last index → 4 → 50  
2️⃣ Move backward by 1 → index 3 → 40  
3️⃣ Move backward → index 2 → 30  
4️⃣ Move backward → index 1 → 20  
5️⃣ Move backward → index 0 → 10  

---

### 🔁 Core Logic

Negative step = reverse direction

👉 step = -1 → move backward  
👉 step = -2 → skip backward  

---

### 📦 Internal Memory View

Array in memory:

[10, 20, 30, 40, 50]

Reverse slicing:

4 → 3 → 2 → 1 → 0  

---

### 🤯 WHY This is Powerful

Instead of writing loops ❌

You can reverse instantly:

ReversedArr[::-1] ⚡

---

### 🚀 REAL USE CASES

• reversing datasets 📊  
• time-series reversal ⏱️  
• undo operations 🔄  
• preprocessing data 🤖  

---

### ⚠️ Edge Cases

ReversedArr[::-2] → skip in reverse  

Example:

[50 30 10]

---

### 💡 FINAL IDEA

Reverse slicing = **traversing array backward using negative step**

Fast 🔁 Efficient ⚡ Very powerful 🔥

## ❓ Concept

After creating NumPy arrays, we often need to **access specific elements from the array**.

NumPy provides a powerful **indexing system** that allows us to retrieve values from arrays using their positions.

Indexing works similarly to Python lists, but it can also be applied to **multi-dimensional arrays**.

In [2]:
import numpy as np 
matrix = np.array([
    [10,20,30],
    [40,50,60]
    ])
matrix[0,1]

np.int64(20)

## 📖 Output & Explanation

The output produced is:

20

This value comes from the **NumPy array indexing operation** performed in the code.

---

### 🔢 Understanding NumPy Indexing

NumPy allows us to access elements using **index positions**.

The syntax used is:

matrix[row_index, column_index]

This means we must specify:

• the **row position**  
• the **column position**

---

### 📍 Index Positions in the Array

The array we created is:

[[10 20 30]
 [40 50 60]]

Let's label the positions:

       column →
        0   1   2
row 0  [10  20  30]

row 1  [40  50  60]

So the value **20** is located at:

row → 0  
column → 1

---

### ⚙ What the Code Did

The code executed:

matrix[0,1]

NumPy interpreted this as:

• go to **row 0**  
• then move to **column 1**

The value stored at that position is:

20

---

### 🚀 Why Indexing is Important

Indexing allows us to:

• retrieve specific values from arrays  
• extract rows or columns  
• manipulate datasets  
• access elements in large numerical datasets

This is extremely important when working with **data analytics and machine learning datasets**.

## ❓ Concept

In 2D arrays, slicing works on both:

• rows 📏  
• columns 📊  

We can extract specific parts of a matrix using slicing.

Syntax:

array[row_slice, column_slice]

In [1]:
import numpy as np

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

matrix[0:2, 1:3]

array([[20, 30],
       [50, 60]])

## 📖 Output & Explanation

The output produced is:

[[20 30]

 [50 60]] 🎯

---

### 🧠 Output Type

array([[20, 30],
       [50, 60]])  
<class 'numpy.ndarray'>

Each element → np.int64

---

### 🔢 Understanding the Matrix

       column →
        0   1   2
row 0  [10  20  30]

row 1  [40  50  60]

row 2  [70  80  90]

---

### ⚙️ What the Code Did

matrix[0:2, 1:3]

Split into two parts:

👉 row slice → 0:2 → rows 0 and 1  
👉 column slice → 1:3 → columns 1 and 2  

---

### 🧠 Step-by-Step Execution

Step 1️⃣ → select rows:

[10 20 30]  
[40 50 60]  

Step 2️⃣ → from these rows, select columns 1 and 2:

→ [20 30]  
→ [50 60]  

---

### 📦 Internal Logic

NumPy works in order:

👉 First select rows  
👉 Then apply column slicing  

---

### 🤯 WHY This is IMPORTANT

Real-world data is always 2D:

• rows = data samples 📊  
• columns = features 🔍  

---

### 🚀 REAL USE CASES

• selecting specific features 📊  
• extracting sub-matrix 📦  
• image cropping 🖼️  
• ML data preprocessing 🤖  

---

### ⚠️ Edge Cases

matrix[:, 1] → full column  

matrix[1, :] → full row  

---

### 🧠 Important Insight (Shape Preservation)

Even though we selected a smaller portion, the result is still a **2D array**.

👉 Why?

Because:

• We selected multiple rows ✅  
• AND multiple columns ✅  

So NumPy preserves structure:

→ output remains a matrix (2D), not a flat array ❗

---

### 📐 Shape Understanding

Original shape:

(3, 3)

Result shape:

(2, 2)

👉 Rows reduced → 3 → 2  
👉 Columns reduced → 3 → 2  

---

### 💡 FINAL IDEA

2D slicing = extracting a block of data while keeping structure intact 🔥

## ❓ Concept

In NumPy, we can select entire rows or entire columns using a special symbol:

:  (colon)

This symbol means → **select everything** in that dimension.

In [7]:
import numpy as np 
matrix = np.array(
    [
        [10,20,30],
        [40,50,60],
        [70,80,90]
    ]
)

matrix[:,1]

array([20, 50, 80])

## 📖 Output & Explanation

The output produced is:

[20 50 80] 🎯

---

### 🧠 Output Type

array([20, 50, 80])  
<class 'numpy.ndarray'>

Each element → np.int64

---

### 🔢 Understanding the Matrix

       column →
        0   1   2
row 0  [10  20  30]

row 1  [40  50  60]

row 2  [70  80  90]

---

### ⚙️ What the Code Did

matrix[:, 1]

Split into:

👉 rows → : → ALL rows  
👉 column → 1 → second column  

---

### 🧠 Step-by-Step Execution

Pick column 1 from each row:

row 0 → 20  
row 1 → 50  
row 2 → 80  

---

### 🤯 IMPORTANT — Dimension Change

Result:

[20 50 80]

👉 This is now a **1D array** ❗

---

### 🧠 WHY Dimension Reduced

Because:

• multiple rows selected ✅  
• only ONE column selected ❗  

So NumPy collapses the column dimension.

---

### 📐 Shape Understanding

Original → (3, 3)  
Result → (3,)

---

### 🚀 REAL USE CASES

• selecting feature column 📊  
• extracting labels 🎯  
• ML preprocessing 🤖  

---

### ⚠️ Edge Case

matrix[1, :] → full row  

---

### 🧠 What ":" Actually Means (Core Logic)

The symbol ":" means:

👉 "Select all indices in that dimension"

So:

matrix[:, 1]

Internally becomes:

matrix[0:3, 1]

👉 Because there are 3 rows (0 to 2)

So ":" = full range automatically

---

### 💡 Key Insight

":" is not magic ❗

It is just a shortcut for:

start → 0  
stop → length of dimension

---

### 💡 FINAL IDEA

: means **select everything in that axis**

Used for extracting full rows or columns easily 🔥

## ❓ Concept

In NumPy, selecting rows and columns may look similar but behaves differently.

Understanding the difference is important to avoid confusion.

In [8]:
import numpy as np

matrix = np.array(
    [
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
]
)

row = matrix[1, :]
col = matrix[:, 1]

row, col

(array([40, 50, 60]), array([20, 50, 80]))

## 📖 Output & Explanation

The output produced is:

(array([40, 50, 60]), array([20, 50, 80])) 🎯

---

### 🧠 First Understand What We Got

We actually got **TWO results**:

1️⃣ Row → [40 50 60]  
2️⃣ Column → [20 50 80]  

👉 Both are NumPy arrays (ndarray)

---

### 🔢 Visual Understanding of Matrix

       column →
        0   1   2
row 0  [10  20  30]

row 1  [40  50  60]

row 2  [70  80  90]

---

### ⚙️ PART 1 — Row Selection 📏

matrix[1, :]

👉 Translation:

• row = 1 → pick second row  
• column = : → pick ALL columns  

---

### 🧠 Step-by-Step (Row)

👉 Go to row 1:

[40 50 60]

👉 Take everything in that row ✅

---

### ⚙️ PART 2 — Column Selection 📊

matrix[:, 1]

👉 Translation:

• row = : → pick ALL rows  
• column = 1 → pick second column  

---

### 🧠 Step-by-Step (Column)

From each row pick column 1:

row 0 → 20  
row 1 → 50  
row 2 → 80  

👉 Result:

[20 50 80] ✅

---

### 🤯 SUPER IMPORTANT DIFFERENCE (CORE IDEA 🔥)

Even though syntax looks similar:

matrix[1, :]  
matrix[:, 1]  

👉 Meaning is COMPLETELY DIFFERENT ❗

---

### 📏 Row Selection

👉 Horizontal movement → across columns  

---

### 📊 Column Selection

👉 Vertical movement → across rows  

---

### 🧠 INTERNAL NUMPY THINKING 💾

NumPy processes like:

matrix[row, column]

So:

• matrix[1, :] → fix row, vary column  
• matrix[:, 1] → vary row, fix column  

---

### 🤯 DIMENSION MAGIC (VERY IMPORTANT 🔥)

Both results become:

👉 1D arrays ❗

Why?

• one dimension is FIXED  
• only one direction remains  

---

### 📐 Shape Insight

Row → (3,)  
Column → (3,)  

👉 NOT (1,3) or (3,1)

---

### 🚀 REAL-WORLD THINKING

Think dataset 📊:

| Sample | Feature1 | Feature2 |
|--------|---------|----------|

👉 Row = one data record 🧾  
👉 Column = one feature 📊  

---

### 💡 So:

• matrix[1, :] → one record  
• matrix[:, 1] → one feature  

---

### ⚠️ COMMON MISTAKE ❌

People think:

row == column ❌  

👉 But:

Row = horizontal  
Column = vertical  

---

### 💡 FINAL IDEA

Row slicing ≠ Column slicing ❗  

👉 Direction changes EVERYTHING 🔥

## ❓ Concept

Sometimes we don’t want elements by position.

We want elements based on **conditions**.

NumPy allows this using **Boolean Indexing**.

This means selecting values using True / False conditions.

In [10]:
import numpy as np 

arr = np.array(
    [10,20,30,40,50]
)

arr[arr > 25]

array([30, 40, 50])

## 📖 Output & Explanation

The output produced is:

[30 40 50] 🎯

---

### 🧠 What Just Happened

We did:

arr[arr > 25]

👉 This is NOT normal indexing ❗

---

### 🔢 Step 1 — Condition Evaluation

arr > 25

NumPy checks each element:

10 > 25 → False ❌  
20 > 25 → False ❌  
30 > 25 → True ✅  
40 > 25 → True ✅  
50 > 25 → True ✅  

---

### 📦 Step 2 — Boolean Array Created

Result becomes:

[False False True True True]

👉 This is called a **Boolean mask** 🎭

---

### ⚙️ Step 3 — Filtering

Now NumPy applies:

arr[mask]

So:

arr[[False False True True True]]

👉 Picks only True positions:

30, 40, 50 ✅

---

### 🤯 CORE IDEA (VERY IMPORTANT 🔥)

Boolean indexing = **filtering using condition**

👉 Not position  
👉 Not slicing  
👉 Logical selection  

---

### 🧠 INTERNAL THINKING

NumPy does:

1️⃣ Evaluate condition  
2️⃣ Create Boolean array  
3️⃣ Apply mask to original array  

---

### 📐 Output Type

array([30, 40, 50])  
<class 'numpy.ndarray'>

---

### 🚀 REAL USE CASES

• filtering dataset 📊  
• removing unwanted values ❌  
• selecting specific conditions 🔍  
• ML preprocessing 🤖  

---

### ⚠️ IMPORTANT

Length of Boolean mask must match array ❗

### 🧠 Mapping Mask to Values (VERY IMPORTANT 🔥)

Let’s match mask with array:

Value →   10   20   30   40   50  
Mask  →  False False True True True  

👉 NumPy keeps only values where mask = True

So result:

30, 40, 50 ✅

---

### 🎯 Key Insight

Boolean mask acts like a **filter or selector** 🎭

👉 True → keep value  
👉 False → discard value  

---

### 🧠 Deep Thinking

Boolean indexing is like saying:

👉 "Give me only values that satisfy this condition"

Not by position ❌  
But by logic ✔️

---

### 💡 FINAL IDEA

Boolean Indexing = **data filtering using logic**

👉 This is where NumPy becomes powerful 🔥🔥🔥